server:
  port: 8081

spring:
  application:
    name: backend

  security:
    basic:
      enabled: false

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        default_schema: dbo
    database-platform: org.hibernate.dialect.SQLServerDialect

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://${ad.server.ip}:1433;databaseName=hmdb;useUnicode=true;characterEncoding=UTF-8;integratedSecurity=false;encrypt=true;trustServerCertificate=true;
    username: sa
    password: qw12qw!@

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  ldap:
    urls: ldaps://MAIN.hm.com:636
    base: DC=hm,DC=com
    username: CN=Administrator,CN=Users,DC=hm,DC=com
    password: "qw12qw!@"
    allowed-networks: "192.168.111.0/24, 172.30.1.0/24"
    ssl:
      enabled: true
      trust-all: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    com.hmws: DEBUG
    org.springframework.ldap: DEBUG
    javax.net.ssl: DEBUG
    com.sun.jndi.ldap: DEBUG

citrix:
  storefront:
    server:
      ip: ${STOREFRONT_SERVER_IP:192.168.111.151}
      base-url: http://${citrix.storefront.server.ip}/Citrix/hmstoreWeb

ad:
  default:
    password: "qw12qw!@"
    email-domain: "hm.com"
  userScript:
    path: "C:\\vm_scripts\\createAdUser.ps1"
  addVmToAdScript:
    path: "C:\\vm_scripts\\addVmToAd.ps1"
  securityScript:
    path: "C:\\vm_scripts\\setVmSecurity.ps1"
  baseVmxTemplate:
    path: "C:\\vm_base_template\\template.vmx"
  vmCreatedIn:
    path: "C:\\win2022"
  vmRun:
    path: "C:\\Program Files (x86)\\VMware\\VMware Workstation\\vmrun.exe"
  server:
    ip: ${MAIN_SERVER_IP:192.168.111.150}
  admin:
    username: "administrator@hm.com"
    userInteractive: "administrator"
    password: "qw12qw!@"

jwt:
  secret: "thisissecretkeysomindyourownbusiness"
  expiration-time: 3600000
  refresh-token:
    expiration-time: 604800
