spring:
  application:
    name: backend

  security:
    basic:
      enabled: false

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
        default_schema: dbo
    database-platform: org.hibernate.dialect.SQLServerDialect

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://172.24.247.150:1433;databaseName=hmdb;useUnicode=true;characterEncoding=UTF-8;integratedSecurity=false;encrypt=true;trustServerCertificate=true;
    username: sa
    password: qw12qw!@

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  data:
    redis:
      host: localhost
      port: 6379

ad:
  default:
    password: "qw12qw!@"
    email-domain: "hm.com"
  userScript:
    path: "C:\\vm_scripts\\createAdUser.ps1"
  addVmToAdScript:
    path: "C:\\vm_scripts\\addVmToAd.ps1"
  securityScript:
    path: "C:\\vm_scripts\\setVmSecurity.ps1"
  baseVmxTemplate:
    path: "C:\\vm_base_template\\template.vmx"
  vmCreatedIn:
    path: "C:\\win2022"
  vmRun:
    path: "C:\\Program Files (x86)\\VMware\\VMware Workstation\\vmrun.exe"
  server:
    ip: "172.24.247.150"
  admin:
    username: "administrator@hm.com"
    userInteractive: "administrator"
    password: "qw12qw!@"

jwt:
  secret: "thisissecretkeysomindyourownbusiness"
  expiration-time: 3600000
  refresh-token:
    expiration-time: 604800

server:
  port: 8081
