spring:
  application:
    name: backend

  security:
    basic:
      enabled: false

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        default_schema: public
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.111.10:5432/hmws?characterEncoding=UTF-8
    username: postgres
    password: qw12qw!@

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

ad:
  default:
    password: "qw12qw!@"
    email-domain: "hw.com"
  userScript:
    path: "C:\\vm_scripts\\createAdUser.ps1"
  addVmToAdScript:
    path: "C:\\vm_scripts\\addVmToAd.ps1"
  securityScript:
    path: "C:\\vm_scripts\\setVmSecurity.ps1"
  baseVmxTemplate:
    path: "C:\\vm_base_template\\template.vmx"
  vmCreatedIn:
    path: "C:\\win2022"
  vmRun:
    path: "C:\\Program Files (x86)\\VMware\\VMware Workstation\\vmrun.exe"
  server:
    ip: "192.168.111.10"
  admin:
    username: "administrator@hanbit.com"
    userInteractive: "administrator"
    password: "qw12qw!@"

jwt:
  secret: "thisissecretkeysomindyourownbusiness"
  expiration-time: 3600000
  refresh-token:
    expiration-time: 604800

server:
  port: 8081
