# .github/workflows/ci.yml
name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "build.gradle"
      - "Dockerfile"
      - "helm/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Generate version
        id: version
        run: |
          echo "BUILD_VERSION=$(date +'%Y%m%d')-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: devhehexd/backend:test-${{ env.BUILD_VERSION }}

      - name: Checkout k8s-manifests repo
        uses: actions/checkout@v3
        with:
          repository: VDI-Workstation-Project/k8s-manifests
          token: ${{ secrets.PAT_TOKEN }}
          path: k8s-manifests

      - name: Update Helm values
        run: |
          cd k8s-manifests/backend/helm
          yq e ".image.tag = \"test-${BUILD_VERSION}\"" -i values.yaml

      - name: Commit and push changes
        run: |
          cd k8s-manifests
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "chore: update backend image to test-${BUILD_VERSION}"
          git push

env:
  DOCKER_BUILDKIT: 1
