# backend/.github/workflows/ci-cd.yml
name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'build.gradle'
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Generate version
        id: version
        run: |
          echo "BUILD_VERSION=$(date +'%Y%m%d')-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: devhehexd/backend:test-${{ env.BUILD_VERSION }}

  update-manifests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout k8s-manifests repo
        uses: actions/checkout@v3
        with:
          repository: VDI-Workstation-Project/k8s-manifests
          token: ${{ secrets.PAT_TOKEN }}
          path: k8s-manifests

      - name: Update image tag in deployment
        run: |
          cd k8s-manifests/backend
          sed -i 's|image: devhehexd/backend:.*$|image: devhehexd/backend:test-${{ env.BUILD_VERSION }}|' backend-deployment.yaml

      - name: Verify manifest files
        run: |
          cd k8s-manifests/backend
          if [ ! -f backend-configmap.yaml ] || [ ! -f backend-secret.yaml ] || [ ! -f backend-deployment.yaml ] || [ ! -f backend-service.yaml ]; then
            echo "Missing required manifest files"
            exit 1
          fi

      - name: Commit and push changes with ordered list
        run: |
          cd k8s-manifests
          echo "Manifest application order:" > backend/README.md
          echo "1. backend-configmap.yaml" >> backend/README.md
          echo "2. backend-secret.yaml" >> backend/README.md
          echo "3. backend-deployment.yaml" >> backend/README.md
          echo "4. backend-service.yaml" >> backend/README.md
          
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Update backend image to test-${{ env.BUILD_VERSION }} and document deployment order"
          git push

env:
  DOCKER_BUILDKIT: 1
